version: 2.1

# 実行環境を定義
executors:
  test_default:
    working_directory: ~/myproject
    docker:
      - image: circleci/python:3.8
        environment:
          PYTHONDONTWRITEBYTECODE: 1
          PYTHONUNBUFFERED: 1
          TZ: Asia/Tokyo
  # test_env:
  #   working_directory: ~/test_env
  #   docker:
  #     - image: circleci/postgres:12.1

# 実行コマンドの定義
commands:
  chown_python_package:
    description: 'pipinstallする権限をcircleciに変更'
    steps:
      - run:
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
  pip_install:
    description: 'pip installを実行'
    steps:
      - run:
          command: |
            pip install pipenv
            pip install django
            python manage.py startapp myapp
  db_migrations:
    description: 'pip installを実行'
    steps:
      - run:
          command: |
            python3 manage.py makemigrations
            python3 manage.py migrate
  save_python_package:
    description: 'Pipinstallしたpackageをキャッシュする'
    steps:
      - save_cache:
        name: Save Python Package
        key: myapp-{{ .Branch }}-{{ checksum 'Pipfile.lock' }}
        paths:
          - 'usr/local/bin'
          - 'usr/local/lib/python3.8/site-packages'

# ジョブの定義
jobs:
  build:
    executor: test_default
    steps:
      - checkout
      - chown_python_package
      - pip_install
      - save_python_package
      - db_migrations
      - run:
          name: test
          command: python manage.py test

# ワークフロー
workflows:
  version: 2.1
  build_only:
    jobs:
      - build