version: 2.1

# 実行環境を定義
executors:
  test_default:
    working_directory: ~/myproject
    docker:
      - image: circleci/python:3.7

# 実行コマンドの定義
commands:
  pip_install:
    description: 'pip installを実行'
    steps:
      - run:
        command: pip3 install -r requirements.txt --user

# ジョブの定義
jobs:
  build:
    executor: test_default
    steps:
      - checkout
      - pip_install




workflows:
  version: 2.1
  build_only:
    jobs:
      - build