version: 2
jobs:
  build:
    working_directory: ~/projects
    docker:
      - image: circleci/python:3.6.4
    steps:
      - run:
          command: |
            sudo pip install pipenv
            pipenv install django
            pipenv run django-admin startproject config .
            pipenv run python3 manage.py startapp myapp
            pipenv run python3 manage.py test
