version: 2.1

#実行環境の定義
executors:
  test_default:
    working_directory: ~/myproject
    docker:
      - image: circleci/python:3.7
        environment:
          PYTHONDONTWRITEBYTECODE: 1
          PYTHONUNBUFFERED: 1
          TZ: Asia/Tokyo

commands:
  pip_install:
    description: 'pip install実行'
    steps:
      - run:
        name: pip install
        command: pip install django

jobs:
  build:
    steps:
      - pip_install
      - run:
        name: start
        command: django-admin startproject config .


workflows:
  version: 2.1
  build:
    jobs:
      - build
    