version: 2.1

# 実行環境を定義
executors:
  test_default:
    working_directory: ~/myproject
    docker:
      - image: circleci/python:3.7

# 実行コマンドの定義
commands:
  pip_install:
    description: 'pip installを実行'
    steps:
      - run:
        name: pip install
        command: pip install django

# ジョブの定義
jobs:
  build:
    executor: test_default
    steps:
      - checkout
      - pip_install
      - run:
          name: test
          command: python3 manage.py test


workflows:
  version: 2.1
  build_only:
    jobs:
      - build