version: 2.1
executors:
  my-executor:
    working_directory: my-projects
    docker:
      - image: circleci/python:3.7
        environment:
          PYTHONDONTWRITEBYTECODE: 1
          PYTHONUNBUFFERED: 1
          TZ: Asia/Tokyo



# ジョブの定義      
jobs:
  my-job:
    executor: my-executor
    steps:

      - run:
        name:
          sudo pipenv install 
          

# ワークフロー
workflows:
  version: 2.1
  build:
    jobs:
      - my-job


