version: 2.1

# 実行環境を定義
executors:
  test_default:
    working_directory: ~/myproject
    docker:
      - image: circleci/python:3.7
        environment:
          PYTHONDONTWRITEBYTECODE: 1
          PYTHONUNBUFFERED: 1
          TZ: Asia/Tokyo
  # test_env:
  #   working_directory: ~/test_env
  #   docker:
  #     - image: circleci/postgres:12.1

# 実行コマンドの定義
commands:
  pip_install:
    description: 'pip installを実行'
    steps:
      - run:
          command: |
            pip install pipenv
            pip install django
            python manage.py startapp myapp
            

# ジョブの定義
jobs:
  build:
    executor: test_default
    steps:
      - checkout
      - pip_install
      - run:
          name: test
          command: python manage.py test

# ワークフロー
workflows:
  version: 2.1
  build_only:
    jobs:
      - build