version: 2
jobs:
  build:
    working_directory: ~/projects
    docker:
      - image: circleci/python:3.6.4
    steps:
      - run:
          command: |
            sudo pip install pipenv
            pipenv shell --fancy
            pipenv install django
            django-admin startproject config .