version: 2.1

#実行環境の定義
executors:
  test_default:
    working_directory: ~/myproject
    docker:
      - image: circleci/python:3.7
        environment:
          PYTHONDONTWRITEBYTECODE: 1
          PYTHONUNBUFFERED: 1
          TZ: Asia/Tokyo



jobs:
  build:
      - run:
        name: start
        command: django-admin startproject config .


workflows:
  version: 2.1
  build:
    jobs:
      - build
    