version: 2.1
executors:
  my-executor:
    working_directory: my-projects
    docker:
      - image: circleci/python:3.7
        environment:
          PYTHONDONTWRITEBYTECODE: 1
          PYTHONUNBUFFERED: 1
          TZ: Asia/Tokyo

jobs:
  my-job:
    executor: my-executor
    steps:
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python:3.7/site-packages
      - run:
          name: install pipenv
          command: sudo pip install pipenv

workflows:
  version: 2.1
  build:
    jobs:
      - my-job





# jobs:
#   build:
#     executor:
#       name: test_default
#     steps:
#       - run:
#           name: test
#           command: |
#             sudo pip install pipenv
#             pipenv install django
#             pipenv run django-admin startproject config .


# jobs:
#   build:
#     executor: my-executor
#     working_directory: ~/projects
#     steps:
#       - run:
#           command: |
#             sudo pip install pipenv
#             pipenv install django
#             pipenv run django-admin startproject config .
#             pipenv run python3 manage.py startapp myapp
#             pipenv run python3 manage.py test
